"""Generate ``THIRD_PARTY_NOTICES.txt`` for the runtime dependency closure.

This satisfies Apache-2.0 §4(d) for downstream redistribution of the
wheel, sdist, and container image.

The canonical source of names + versions is the hash-locked Docker
runtime lockfile [`docker/requirements-runtime.txt`]. That lockfile is
what actually ships in the published container image. The current
Python environment is used only to resolve license/notice text from
each package's installed metadata via ``pip-licenses``; the env's
resolver outcome is **not** the source of truth.

Usage::

    python scripts/generate_third_party_notices.py > THIRD_PARTY_NOTICES.txt

Recommended setup (matches the CI workflow exactly so the file
regenerates byte-for-byte regardless of where it runs)::

    pip install --require-hashes -r docker/requirements-runtime.txt
    pip install --no-deps -e ".[keyring]"
    pip install pip-licenses
    python scripts/generate_third_party_notices.py > THIRD_PARTY_NOTICES.txt

The ``--no-deps`` on the project install is mandatory: without it pip
will silently re-resolve the runtime closure and the env may diverge
from the lockfile, which defeats the whole point of pinning.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

# Distribution names that should never appear in the notices because
# they are this project itself.
SELF_NAMES = frozenset({"spl-bridge", "spl_bridge"})

HEADER = """\
THIRD-PARTY SOFTWARE NOTICES AND INFORMATION
============================================

This file lists the third-party open-source software that ``spl-bridge``
depends on at runtime. It is generated by
``scripts/generate_third_party_notices.py`` from the hash-locked Docker
runtime requirements file ``docker/requirements-runtime.txt``, which is
the authoritative source of what actually ships in the published
container image.

For each package the file records:

  - Name and version as pinned in the Docker runtime lockfile
  - SPDX license expression as reported by the package's metadata
  - Verbatim text of the package's LICENSE file when available
  - Verbatim text of the package's NOTICE file when available
    (Apache-2.0 §4(d) attribution carry-through)

Wheel / sdist consumers: pip's resolver may pick patch versions of
these dependencies that differ from the pinned versions below; the
authoritative attribution payload for any given build is the
``THIRD_PARTY_NOTICES.txt`` shipped in that build's artefacts (the
wheel's ``*.dist-info/`` directory, the sdist tarball root, or
``/licenses/THIRD_PARTY_NOTICES.txt`` in the container image).

This file is included in the published wheel and sdist via
``[project].license-files`` in ``pyproject.toml``, and copied into the
container image at ``/licenses/THIRD_PARTY_NOTICES.txt``.

If you are bumping a runtime dependency, regenerate this file in the
same commit (the legal-hygiene CI job will fail the build otherwise).

"""


def _strip_spec(spec: str) -> str:
    """Strip version / extras / marker from a single requirement and
    return the bare distribution name.

    Finds the *earliest* version-spec / extras / whitespace boundary so
    that requirements like ``urllib3<3,>=1.26`` parse to ``urllib3``
    rather than ``urllib3<3,``.
    """
    head = spec.split(";", 1)[0]
    cut_indices = [head.find(sep) for sep in ("<", ">", "=", "~", "!", "[", " ")]
    cut = min((i for i in cut_indices if i >= 0), default=-1)
    if cut >= 0:
        head = head[:cut]
    return head.strip()


def _canon(name: str) -> str:
    """PEP 503-style canonical distribution name (case-insensitive,
    underscores / dots normalised to hyphens)."""
    return name.lower().replace("_", "-").replace(".", "-")


def lockfile_pinned_versions(lockfile: Path) -> dict[str, str]:
    """Parse a ``pip-compile --generate-hashes`` lockfile into a
    ``{canonical-name: pinned-version}`` mapping.

    Each top-level requirement line in the lockfile is of the form
    ``<name>==<version> \\`` followed by hash continuation lines and
    ``# via ...`` comments. We only keep the ``<name>==<version>`` head.
    """
    if not lockfile.exists():
        raise FileNotFoundError(
            f"Docker runtime lockfile not found: {lockfile}. "
            "Generate it via scripts/refresh_docker_requirements.sh."
        )
    pinned: dict[str, str] = {}
    for raw in lockfile.read_text(encoding="utf-8").splitlines():
        line = raw.strip()
        if not line or line.startswith("#") or line.startswith("--hash="):
            continue
        if line.endswith("\\"):
            line = line[:-1].strip()
        if "==" not in line:
            continue
        head, _, ver = line.partition("==")
        name = _canon(_strip_spec(head))
        ver = _strip_spec(ver)
        if name and ver and name not in {_canon(s) for s in SELF_NAMES}:
            pinned[name] = ver
    return pinned


def env_packages() -> dict[str, dict]:
    """Run ``pip-licenses`` against the current environment and return
    a ``{canonical-name: piplicenses_record}`` mapping. The records are
    used purely for license/notice text resolution; the env is *not*
    the source of truth for which packages ship."""
    out = subprocess.check_output(
        [
            sys.executable,
            "-m",
            "piplicenses",
            "--format=json",
            "--with-license-file",
            "--with-notice-file",
            "--no-license-path",
            "--with-urls",
        ],
        text=True,
    )
    return {_canon(p["Name"]): p for p in json.loads(out)}


def collect_packages(lockfile: Path) -> tuple[list[dict], list[str]]:
    """Build the package list to render and a list of human-readable
    sanity-check warnings.

    The list is the lockfile contents, joined to the env's pip-licenses
    metadata for license text. Warnings are emitted (but do not fail)
    when the env disagrees with the lockfile -- e.g., a different
    version is installed, or a package is missing entirely. CI installs
    from the lockfile before running this script, so warnings should be
    empty in CI; locally they tell developers their venv has drifted.
    """
    pinned = lockfile_pinned_versions(lockfile)
    env = env_packages()

    rendered: list[dict] = []
    warnings: list[str] = []
    self_canon = {_canon(s) for s in SELF_NAMES}
    for name in sorted(pinned):
        if name in self_canon:
            continue
        record = env.get(name)
        locked_version = pinned[name]
        if record is None:
            warnings.append(
                f"package {name}=={locked_version} is in the Docker lockfile "
                "but not installed in the current environment; "
                "license/notice text cannot be embedded for it. "
                "Run: pip install --require-hashes -r docker/requirements-runtime.txt"
            )
            rendered.append(
                {
                    "Name": name,
                    "Version": locked_version,
                    "License": "UNKNOWN (env drift)",
                    "URL": "UNKNOWN",
                    "LicenseText": "[license text unavailable: package not installed in regen env]",
                    "NoticeText": "",
                }
            )
            continue
        env_version = record.get("Version", "")
        if env_version and env_version != locked_version:
            warnings.append(
                f"version drift for {name}: lockfile {locked_version} vs env {env_version}; "
                "embedded license text reflects env version"
            )
        rendered.append(
            {
                "Name": record.get("Name", name),
                "Version": locked_version,
                "License": record.get("License", "UNKNOWN"),
                "URL": record.get("URL", "UNKNOWN"),
                "LicenseText": record.get("LicenseText"),
                "NoticeText": record.get("NoticeText"),
            }
        )

    extra_in_env = sorted(set(env) - set(pinned) - self_canon)
    if extra_in_env:
        warnings.append(
            "the current environment has packages NOT in the Docker lockfile "
            f"(ignored): {', '.join(extra_in_env[:10])}" + ("..." if len(extra_in_env) > 10 else "")
        )

    return rendered, warnings


def render(pkgs: list[dict]) -> str:
    parts: list[str] = [HEADER]
    parts.append(
        f"Generated for {len(pkgs)} package(s):\n  "
        + ", ".join(f"{p['Name']}=={p['Version']}" for p in pkgs)
        + "\n\n"
    )
    bar = "=" * 78 + "\n"
    for p in pkgs:
        parts.append(bar)
        parts.append(f"Package: {p['Name']}\n")
        parts.append(f"Version: {p['Version']}\n")
        parts.append(f"License: {p.get('License', 'UNKNOWN')}\n")
        url = p.get("URL", "UNKNOWN")
        if url and url != "UNKNOWN":
            parts.append(f"Project: {url}\n")
        parts.append("\n--- LICENSE ---\n\n")
        license_text = p.get("LicenseText") or "[no LICENSE file shipped in distribution metadata]"
        parts.append(license_text.rstrip() + "\n")
        notice = p.get("NoticeText")
        if notice and notice.strip() and notice.strip().upper() != "UNKNOWN":
            parts.append("\n--- NOTICE ---\n\n")
            parts.append(notice.rstrip() + "\n")
        parts.append("\n")
    return "".join(parts)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--docker-lockfile",
        type=Path,
        default=Path("docker/requirements-runtime.txt"),
        help="Hash-locked runtime requirements file used by the container image "
        "(authoritative source of names and versions).",
    )
    args = ap.parse_args()
    pkgs, warnings = collect_packages(args.docker_lockfile)
    for w in warnings:
        print(f"[generate_third_party_notices] WARN: {w}", file=sys.stderr)
    sys.stdout.write(render(pkgs))
    return 0


if __name__ == "__main__":
    sys.exit(main())
